import { UserDTO } from '@/modules/search/queries/searchQuery';
import { EnumGender } from './genders';
import { lang, proficiency } from './languages';

export type UserType = 'fisica' | 'moral';

export interface IFirebaseProfile {
  birthday?: string;
  workRadius?: string;
  youtube?: string;
  whatsapp?: string;
  country?: string;
  gender?: EnumGender;
  city?: string;
  university?: string;
  postalCode?: string;
  coverPictureUrl?: string;
  created?: boolean;
  linkedin?: string;
  instagram?: string;
  type: UserType;
  twitter?: string;
  imdb?: string;
  reviews?: string;
  tiktok?: string;
  altEmail?: string;
  nickname?: string;
  state?: string;
  headline?: string;
  email: string;
  profilePictureUrl?: string;
  subareas?: string[];
  characteristics?: string;
  website?: string;
  address?: string;
  languages?: { lang: lang; proficiency: proficiency }[];
  remoteWork?: boolean;
  facebook?: string;
  googleMapsLink?: string;
  certifications?: string;
  lastname?: string;
  asociations?: string;
  profilePicture?: string;
  vimeo?: string;
  altEmail2?: string;
  phone?: string;
  awards?: string;
  probono?: boolean;
  searchName: string[];
  name?: string;
  altPhone?: string;
  location?: string;
  altPhone2?: string;
  reviewCount?: number;
}

export interface IBackendProfile {
  address?: string;
  associations?: string;
  awards?: string;
  birthday?: string;
  certifications?: string;
  characteristics?: string;
  city?: string;
  country?: string;
  coverPictureUrl?: string;
  created?: boolean;
  facebook?: string;
  firstName?: string;
  fullName?: string;
  gender?: EnumGender;
  googleMapsLink?: string;
  headline?: string;
  id: string;
  imdb?: string;
  instagram?: string;
  languages?: { lang: lang; proficiency: proficiency }[];
  lastName?: string;
  linkedin?: string;
  location?: string;
  nickname?: string;
  phoneNumbers?: string[];
  postalCode?: string;
  primaryActivity?: string;
  primaryEmail: string;
  probono?: boolean;
  profilePicture?: string;
  profilePictureUrl?: string;
  recommendations?: UserDTO[];
  recommendationsCount: number;
  remote?: boolean;
  secondaryActivity?: string;
  secondaryEmails?: string[];
  state?: string;
  thirdActivity?: string;
  tiktok?: string;
  twitter?: string;
  type: UserType;
  university?: string;
  vimeo?: string;
  externalLinks?: string[];
  whatsapp?: string;
  workRadius?: string;
  youtube?: string;
}
export interface IUpdateBackendProfile {
  address?: string;
  associations?: string;
  awards?: string;
  birthday?: string;
  certifications?: string;
  characteristics?: string;
  city?: string;
  country?: string;
  coverPictureUrl?: string;
  facebook?: string;
  firstName?: string;
  gender?: EnumGender;
  googleMapsLink?: string;
  headline?: string;
  imdb?: string;
  instagram?: string;
  languages?: { lang: lang; proficiency: proficiency }[];
  lastName?: string;
  linkedin?: string;
  nickname?: string;
  phoneNumbers?: string[];
  postalCode?: string;
  primaryActivity?: string;
  probono?: string | boolean;
  profilePicture?: string;
  profilePictureUrl?: string;
  remote?: boolean | string;
  secondaryActivity?: string;
  secondaryEmails?: string[];
  state?: string;
  thirdActivity?: string;
  tiktok?: string;
  twitter?: string;
  university?: string;
  vimeo?: string;
  externalLinks?: string[];
  whatsapp?: string;
  workRadius?: string;
  youtube?: string;
}
